name: Build AdBlodID

on:
  schedule:
    - cron:  '1 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up python-abp
      run: |
        pip install -e tools/python-abp
    - name: Build AdBlockID
      run: |
        sh ./build.sh
    - name: Commit files
      run: |
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config user.name "${{ secrets.GIT_USER_NAME }}"
        git commit -m "${{ secrets.GIT_COMMIT_MSG }}" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
