name: Labeling new issue
on:
  issues:
      types: ['opened', 'edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2 # or v2.1.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-synonyms: '{"C: Annoyance":["embed","copy paste","copy-paste","klik kanan","klik-kanan","overlay","right click","right-click"],"C: NSFW":["bercinta","binor","bokep","dewasa","hentai","memek","mesum","ngewe","perawan","sange","sex","threesome"],"C: Pop-up ads":["Popup","pop-up"],"C: safelink":["safelink"],"R: Invalid":["ivalid"],"R: Duplicate":["duplicate"],"C: International":["international"],"C: Anti-Adblock":["anti adblock","anti-adblock"],"C: Tracker":["privacy","tracker"]}'
          labels-not-allowed: '["potential-duplicate"]'
          default-labels: '["C: Native"]'
