name: 'Label Actions'

on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]

jobs:
  reaction:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

# Configuration for Label Actions - https://github.com/dessant/label-actions

# Actions taken when the `R: Invalid` label is added to issues or pull requests
Needs more info:
  # Post a comment
  comment: >
    It has not been resolved completely or only partially.
